'use strict';
const assert = require('node:assert/strict');
const o = require('./ticket011-opportunity-engine.cjs');
const TS = '2026-07-17T20:00:00.000Z';
let pass = 0;
function test(name, fn) { try { fn(); pass++; console.log(`PASS ${name}`); } catch (e) { console.error(`FAIL ${name}: ${e.message}`); process.exitCode = 1; } }
function eligible(overrides = {}) { return { page_id: 'page-x', canonical_page_path: '/x', primary_task_family: 'how_to_task', metric_family: 'gsc_ctr', signal_family: 'acquisition_discovery', state: 'INVESTIGATION_ELIGIBLE', settlement_state: 'settled', window_start: '2026-07-01', window_end: '2026-07-07', detected_at: '2026-07-17T20:00:00.000Z', measurement_status: 'MEASURED', sample_state: 'decision_eligible', evidence_grade: 'E1', peer_policy_version: 'metric-peer-policy.v1', peer_cell_id: 'gsc_ctr:0:how_to', peer_fallback_level: 0, posterior_mean: 0.03, posterior_interval_80_low: 0.02, posterior_interval_80_high: 0.04, posterior_interval_95_low: 0.01, posterior_interval_95_high: 0.05, probability_below_practical_delta: 0.91, practical_delta: 0.02, task_contract_status: 'CONFIRMED', ...overrides }; }
console.log('Ticket 011 — governed opportunity-engine tests');

test('contract version is explicit', () => assert.equal(o.CONTRACT_VERSION, 'ticket-011.v1'));
test('opportunity schema version is explicit', () => assert.equal(o.OPPORTUNITY_SCHEMA_VERSION, 'opportunity.v0.5'));
test('eligible row passes filter', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible()] }); assert.equal(out.case_count, 1); });
test('fresh row cannot create case', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible({ settlement_state: 'fresh' })] }); assert.equal(out.case_count, 0); });
test('blocked row cannot create case', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible({ measurement_status: 'MEASUREMENT_BLOCKED' })] }); assert.equal(out.case_count, 0); });
test('raw metric row without transition cannot create case', () => { const out = o.buildOpportunityEngine({ rows: [eligible({ state: undefined })] }); assert.equal(out.case_count, 0); });
test('case has required identity fields', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; for (const key of ['opportunity_id','opportunity_schema_version','created_at','updated_at','state','state_version','deduplication_key','page_id','canonical_path','metric_family','signal_family']) assert.ok(c[key] != null, key); });
test('opportunity ID survives evidence refresh', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible(), eligible({ window_start: '2026-07-08', window_end: '2026-07-14', posterior_mean: 0.02 })] }); assert.equal(out.case_count, 1); assert.equal(out.cases[0].opportunity_id, out.event_ledger[0].opportunity_id); });
test('duplicate unresolved cases are not created', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible(), eligible(), eligible()] }); assert.equal(out.case_count, 1); assert.equal(out.duplicate_unresolved_cases, 0); assert.equal(out.event_ledger.length, 3); });
test('immutable detection snapshot is present', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.ok(c.immutable_detection_snapshot); assert.equal(c.immutable_detection_snapshot.window_start, '2026-07-01'); });
test('immutable detection snapshot preserves top-level Ticket 010 release IDs', () => {
  const c = o.buildOpportunityEngine({ derived_evidence: [eligible({ canonical_release_id: 'rel_0123456789abcdef', acquisition_release_id: 'run_0123456789abcdef' })] }).cases[0];
  assert.deepEqual(c.immutable_detection_snapshot.source_release_ids, {
    canonical_release_id: 'rel_0123456789abcdef',
    acquisition_release_id: 'run_0123456789abcdef',
  });
});
test('final packet generation rejects missing detected_at instead of using wall clock time', () => {
  assert.throws(() => o.buildOpportunityEngine({ derived_evidence: [eligible({ detected_at: null })] }), /detected_at/);
});
test('final packet generation is byte-stable for identical timestamped evidence', () => {
  const input = { derived_evidence: [eligible()] };
  assert.equal(JSON.stringify(o.buildOpportunityEngine(input)), JSON.stringify(o.buildOpportunityEngine(input)));
});
test('current evidence refreshes without overwriting detection snapshot', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible({ posterior_mean: 0.03 }), eligible({ posterior_mean: 0.01, window_start: '2026-07-08' })] }); assert.equal(out.cases[0].immutable_detection_snapshot.posterior_summary.posterior_mean, 0.03); assert.equal(out.cases[0].current_evidence_summary.posterior_mean, 0.01); });
test('E0/E1 causal language is constrained', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible({ evidence_grade: 'E1' })] }).cases[0]; assert.equal(c.causal_language_allowed, false); assert.equal(o.causalLanguageAllowed('E0'), false); });
test('tail-selection flag exists', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible({ selected_from_extreme_tail: true })] }).cases[0]; assert.equal(c.selected_from_extreme_tail, true); });
test('bounded hypothesis families are created', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; for (const id of ['H0_NO_ACTION_OR_NOISE','MEASUREMENT_OR_CLASSIFICATION','DEMAND_OR_QUERY_MIX','PACKAGING_OR_TASK_PROMISE','PAGE_CONTENT_OR_UX','CHANGE_CONTAMINATION']) assert.ok(c.hypotheses.some((h) => h.hypothesis_id === id)); });
test('task mismatch adds task ownership hypothesis', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible({ promise_task_alignment: 'QUERY_PROMISE_MISMATCH' })] }).cases[0]; assert.ok(c.hypotheses.some((h) => h.hypothesis_id === 'TASK_OWNERSHIP_REVIEW')); });
test('diagnostic plan declares hypotheses and no production touch', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.ok(c.diagnostic_plan.length >= 5); assert.ok(c.diagnostic_plan.every((d) => d.production_touch === false)); });
test('authority distinguishes A1 investigation from A4 production', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.equal(c.authority.investigation_authority_level, 'A1'); assert.equal(c.authority.production_edit_authority, 'A4_REQUIRED'); });
test('case starts without proposal', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.deepEqual(c.proposal_ids, []); assert.equal(c.recommendation_or_edit_instruction, null); });
test('diagnostic update requires declared diagnostic', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.throws(() => o.applyDiagnosticUpdate(c, { executed_at: TS, diagnostic_id: 'D_UNKNOWN' }), /not declared/); });
test('production touch is rejected as diagnostic', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.throws(() => o.applyDiagnosticUpdate(c, { executed_at: TS, diagnostic_id: 'D_QUERY_INTENT_DECOMPOSITION', production_touch: true }), /production edits/); });
test('diagnostic updates every live ledger path', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; const next = o.applyDiagnosticUpdate(c, { executed_at: TS, diagnostic_id: 'D_QUERY_INTENT_DECOMPOSITION', result_summary: 'query mix changed', supporting_hypotheses: ['DEMAND_OR_QUERY_MIX'], contradicting_hypotheses: ['PACKAGING_OR_TASK_PROMISE'], supported_hypotheses: ['DEMAND_OR_QUERY_MIX'], input_provenance: 'fixture' }); assert.equal(next.state, 'INVESTIGATING'); assert.equal(next.diagnostic_ledger.length, 1); assert.equal(next.hypotheses.find((h) => h.hypothesis_id === 'DEMAND_OR_QUERY_MIX').status, 'SUPPORTED_NOT_CAUSAL'); assert.ok(next.hypotheses.find((h) => h.hypothesis_id === 'PACKAGING_OR_TASK_PROMISE').contradicting_observations.length); });
test('diagnostic status does not claim causal proof', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; const next = o.applyDiagnosticUpdate(c, { executed_at: TS, diagnostic_id: 'D_CHANGE_MANIFEST_JOIN', result_summary: 'overlap found', supported_hypotheses: ['CHANGE_CONTAMINATION'] }); assert.equal(next.hypotheses.find((h) => h.hypothesis_id === 'CHANGE_CONTAMINATION').status, 'SUPPORTED_NOT_CAUSAL'); });
test('diagnostic update rejects a missing explicit execution timestamp', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.throws(() => o.applyDiagnosticUpdate(c, { diagnostic_id: 'D_CHANGE_MANIFEST_JOIN' }), /executed_at/); });
test('resolution codes are bounded', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.throws(() => o.resolveInvestigation(c, { resolved_at: TS, resolution_code: 'REWRITE_PAGE' }), /invalid resolution/); });
test('zero-action resolution is supported', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; const next = o.resolveInvestigation(c, { resolved_at: TS, resolution_code: 'NO_ACTION_SUPPORTED', resolution_summary: 'not practically meaningful' }); assert.equal(next.state, 'INVESTIGATION_RESOLVED'); assert.equal(next.resolution.proposal_allowed, false); });
test('intervention resolution permits only a later proposal draft', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; const next = o.resolveInvestigation(c, { resolved_at: TS, resolution_code: 'INTERVENTION_CANDIDATE', leading_hypotheses: ['PACKAGING_OR_TASK_PROMISE'], evidence_grade: 'E1' }); assert.equal(next.resolution.proposal_allowed, true); assert.equal(next.state, 'INVESTIGATION_RESOLVED'); });
test('resolution rejects a missing explicit resolution timestamp', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.throws(() => o.resolveInvestigation(c, { resolution_code: 'NO_ACTION_SUPPORTED' }), /resolved_at/); });
test('proposal cannot be drafted before resolution', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.throws(() => o.buildProposalDraft(c), /requires eligible investigation resolution/); });
test('proposal draft rejects a missing explicit creation timestamp', () => { let c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; c = o.resolveInvestigation(c, { resolved_at: TS, resolution_code: 'INTERVENTION_CANDIDATE' }); assert.throws(() => o.buildProposalDraft(c, {}), /created_at/); });
test('proposal draft has typed change and authority fields', () => { let c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; c = o.resolveInvestigation(c, { resolved_at: TS, resolution_code: 'INTERVENTION_CANDIDATE', leading_hypotheses: ['PACKAGING_OR_TASK_PROMISE'], evidence_grade: 'E1' }); const x = o.buildProposalDraft(c, { created_at: TS, intervention_hypothesis: 'packaging treatment', change_surface: 'title_meta', exact_routes_or_components: ['/x'], proposed_treatment: 'draft only', primary_metric: 'gsc_ctr', eligible_population: 'settled nonbranded queries', minimum_practical_effect: 0.02, harm_threshold: 0.03, guardrail_metrics: ['progression_rate'], maximum_horizon: '28d', decision_rule: 'pre-specified', rollback_procedure: 'git revert' }); assert.equal(x.validation.valid, true); assert.equal(x.proposal.required_authority_level, 'A4'); assert.equal(x.proposal.current_authorization_state, 'NOT_AUTHORIZED'); });
test('proposal validation rejects missing fields', () => { assert.equal(o.validateInterventionProposal({}).valid, false); });
test('proposal validation rejects wrong causal target', () => { const x = o.validateInterventionProposal({ proposal_id:'p', opportunity_id:'o', proposal_schema_version:'v', status:'DRAFT', intervention_hypothesis:'x', change_surface:'x', exact_routes_or_components:[], proposed_treatment:'x', primary_metric:'x', eligible_population:'x', minimum_practical_effect:0.1, harm_threshold:0.1, guardrail_metrics:[], maximum_horizon:'x', decision_rule:'x', rollback_procedure:'x', required_authority_level:'A4', current_authorization_state:'NOT_AUTHORIZED', production_touch:false, causal_evidence_target:'E1' }); assert.equal(x.valid, false); assert.ok(x.errors.includes('causal_evidence_target must target E2/E3/E4')); });
test('proposal validation rejects production-touch diagnostics', () => { const x = o.validateInterventionProposal({ production_touch: true }); assert.equal(x.valid, false); assert.ok(x.errors.includes('production_touch must be false until authorized')); });
test('task mismatch routes through ownership investigation', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible({ promise_task_alignment: 'PROMISE_BODY_MISMATCH' })] }).cases[0]; assert.ok(c.diagnostic_plan.some((d) => d.diagnostic_id === 'D_TASK_OWNERSHIP_PACKET')); });
test('no production mutation assertion is explicit', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible()] }); assert.equal(out.no_production_mutation, true); assert.equal(out.no_recommendations_assertion, true); });
test('case state is investigation eligible, not recommendation', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.equal(c.state, 'INVESTIGATION_ELIGIBLE'); assert.notEqual(c.state, 'INTERVENTION_PROPOSED'); });
test('event ledger is append-only shaped', () => { const out = o.buildOpportunityEngine({ derived_evidence: [eligible(), eligible({ window_start: '2026-07-08' })] }); assert.equal(out.event_ledger.length, 2); assert.ok(out.event_ledger.every((e) => e.event === 'EVIDENCE_REFRESH')); });
test('hypothesis status can be rejected', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; const next = o.applyDiagnosticUpdate(c, { executed_at: TS, diagnostic_id: 'D_CHANGE_MANIFEST_JOIN', rejected_hypotheses: ['CHANGE_CONTAMINATION'], result_summary: 'no overlap' }); assert.equal(next.hypotheses.find((h) => h.hypothesis_id === 'CHANGE_CONTAMINATION').status, 'REJECTED'); });
test('evidence grade is mandatory and bounded', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible({ evidence_grade: 'E9' })] }).cases[0]; assert.equal(c.evidence_grade, 'E1'); assert.ok(o.EVIDENCE_GRADES.includes(c.evidence_grade)); });
test('proposal has no authorization hash before human signoff', () => { let c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; c = o.resolveInvestigation(c, { resolved_at: TS, resolution_code: 'EDITORIAL_TASK_OWNERSHIP_REVIEW', leading_hypotheses: ['TASK_OWNERSHIP_REVIEW'] }); const x = o.buildProposalDraft(c, { created_at: TS, intervention_hypothesis: 'ownership review', change_surface: 'content', exact_routes_or_components: ['/x'], proposed_treatment: 'draft', primary_metric: 'gsc_ctr', eligible_population: 'queries', minimum_practical_effect: 0.02, harm_threshold: 0.03, guardrail_metrics: [], maximum_horizon: '28d', decision_rule: 'pre-specified', rollback_procedure: 'revert' }); assert.equal(x.proposal.authorization_scope_hash, null); });
test('diagnostic ledger records evidence quality', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; const next = o.applyDiagnosticUpdate(c, { executed_at: TS, diagnostic_id: 'D_PROMISE_BODY_CONTRACT_AUDIT', evidence_quality: 'strong', result_summary: 'aligned' }); assert.equal(next.diagnostic_ledger[0].evidence_quality, 'strong'); });
test('contract lists no automatic causal upgrade', () => { const c = o.buildOpportunityEngine({ derived_evidence: [eligible()] }).cases[0]; assert.equal(c.causal_language_allowed, false); });

console.log(`Tests: ${pass}/45 passed.`);
if (process.exitCode) process.exit(1);
